[project]
name = "tablemagnifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "dotenv>=0.9.9",
    "google-generativeai>=0.3.0",
    "ipykernel>=7.1.0",
    "langchain>=0.1.0",
    "langchain-core>=0.1.0",
    "langchain-google-genai>=4.0.0",
    "langchain-openai>=1.1.0",
    "langgraph>=0.0.30",
    "pymupdf>=1.26.7",
    "pyyaml>=6.0",
    "typing-extensions>=4.5.0",
    "fastapi>=0.115.0",
    "uvicorn>=0.32.0",
    "python-multipart>=0.0.12",
    "langchain-anthropic>=0.3.0",
    "json-repair>=0.25.3",
    "pandas>=2.3.3",
    "pandasql>=0.7.3",
    "langchain-experimental>=0.4.1",
    "agentsjson==0.1.13",
    "dspydantic>=0.0.7",
    "pydantic>=2.12.4",
    "dspy-ai>=3.0.4",
    "pymongo>=4.6.1",
    "langgraph-checkpoint-sqlite>=3.0.1",
    "notion-client>=2.0.0",
    "playwright>=1.57.0",
]
