[project]
name = "tablemagnifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "dotenv>=0.9.9",
    "google-generativeai>=0.3.0",
    "ipykernel>=7.1.0",
    "langchain>=0.1.0",
    "langchain-core>=0.1.0",
    "langchain-google-genai>=4.0.0",
    "langchain-openai>=1.1.0",
    "langgraph>=0.0.30",
    "pymupdf>=1.26.7",
    "pyyaml>=6.0",
    "typing-extensions>=4.5.0",
    "fastapi>=0.124.4",
    "uvicorn>=0.38.0",
    "python-multipart>=0.0.21",
    "langchain-anthropic>=0.3.0",
    "json-repair>=0.25.3",
    "pandas>=2.3.3",
    "pandasql>=0.7.3",
    "langchain-experimental>=0.4.1",
    "agentsjson==0.1.13",
    "dspydantic>=0.0.7",
    "pydantic>=2.12.4",
    "dspy-ai>=3.0.4",
    "pymongo>=4.6.1",
    "dnspython>=2.8.0",
    "httpx>=0.28.0",
    "tqdm>=4.67.0",
    "requests>=2.32.0",
    "google-api-python-client>=2.187.0",
    "oauth2client>=4.1.3",
    "httplib2>=0.31.0",
]
